version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: null
  default_tier: null
current:
  spec: .specwright/specs/email-body-projection.md
  aip: /workspace/lorchestra/.specwright/aips/email-body-projection.yaml
