version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/dry-run-test-table.md
  aip: .specwright/aips/dry-run-test-table.yaml
