version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/ingestion-to-bq.md
  aip: /workspace/lorchestra/.specwright/aips/ingestion-to-bq.yaml
