version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/object-source-nomanclaure.md
  aip: /workspace/lorchestra/.specwright/aips/standardize-source-system-columns.yaml
