version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: benthepsychologist
  default_tier: C
current:
  spec: .specwright/specs/projector-update-with-config-and-local-files-update.md
  aip: /workspace/lorchestra/.specwright/aips/projector-update-with-config-and-local-files-update.yaml
