#!/bin/bash
#
# Auto-setup BigQuery after manual credential creation
#
# This runs automatically after you've created the service account key.
#
# Usage:
#   bash scripts/auto_setup.sh /path/to/key.json

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

error() {
    echo -e "${RED}ERROR: $1${NC}" >&2
    exit 1
}

success() {
    echo -e "${GREEN}✓ $1${NC}"
}

info() {
    echo -e "${BLUE}→ $1${NC}"
}

# Check argument
if [ -z "$1" ]; then
    error "Usage: bash scripts/auto_setup.sh /path/to/key.json"
fi

CREDENTIALS_FILE="$1"

# Validate credentials file
if [ ! -f "$CREDENTIALS_FILE" ]; then
    error "Credentials file not found: $CREDENTIALS_FILE"
fi

info "Validating credentials file..."
if ! python3 -c "import json; json.load(open('$CREDENTIALS_FILE'))" 2>/dev/null; then
    error "Invalid JSON in credentials file"
fi
success "Credentials file is valid JSON"

# Extract project from credentials
PROJECT=$(python3 -c "import json; print(json.load(open('$CREDENTIALS_FILE'))['project_id'])")
info "Detected project: $PROJECT"

if [ "$PROJECT" != "local-orchestration" ]; then
    echo -e "${YELLOW}Warning: Expected project 'local-orchestration', got '$PROJECT'${NC}"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Set environment variables
export GCP_PROJECT="$PROJECT"
export DATASET_NAME="events_dev"
export GOOGLE_APPLICATION_CREDENTIALS="$CREDENTIALS_FILE"

echo ""
echo "=========================================="
echo "Auto-Setup Starting"
echo "=========================================="
echo "Project: $GCP_PROJECT"
echo "Dataset: $DATASET_NAME"
echo "Credentials: $CREDENTIALS_FILE"
echo "=========================================="
echo ""

# Run Python setup
info "Running BigQuery setup..."
python3 scripts/setup_bigquery.py

# Create .env file
info "Creating .env file..."
cat > .env << EOF
# BigQuery Configuration for lorchestra Event Pipeline
# Generated by auto_setup.sh on $(date)

# Google Cloud Project
GCP_PROJECT=$GCP_PROJECT

# BigQuery Dataset
EVENTS_BQ_DATASET=$DATASET_NAME

# BigQuery Tables
EVENT_LOG_TABLE=event_log
RAW_OBJECTS_TABLE=raw_objects

# Service Account Credentials
GOOGLE_APPLICATION_CREDENTIALS=$CREDENTIALS_FILE
EOF
success "Created .env file"

# Verify setup
info "Verifying setup..."
source .env
python3 scripts/verify_setup.py

echo ""
echo "=========================================="
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo "=========================================="
echo ""
echo "Your BigQuery environment is ready."
echo ""
echo "Next steps:"
echo "  1. Configure Meltano taps in /workspace/ingestor"
echo "  2. Run your first ingestion:"
echo "     source .env"
echo "     lorchestra run-job lorchestra gmail_ingest_acct1"
echo ""
echo "  3. View your data:"
echo "     python3 scripts/query_events.py"
echo ""
